import json
import os

import xacro
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, ExecuteProcess, TimerAction
from launch.conditions import IfCondition
from launch.substitutions import EqualsSubstitution, LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    # Generated by Robotbase from robot.yaml / world.yaml — edit the specs, not this file.
    desc_share = get_package_share_directory("warehouse_bot_description")
    world = os.path.join(desc_share, "worlds", "warehouse.sdf")
    urdf_xacro = os.path.join(desc_share, "urdf", "warehouse_bot.urdf.xacro")
    robot_desc = xacro.process_file(urdf_xacro).toxml()

    # The ROS<->gz bridge list is compiled from the robot's actual sensors (urdf/bridges.json), so an
    # authored camera/depth/extra sensor is bridged, not just rendered in gz. Fall back to the
    # essential drivetrain bridges if the file is missing (e.g. a hand-edited legacy project).
    bridges_json = os.path.join(desc_share, "urdf", "bridges.json")
    if os.path.exists(bridges_json):
        with open(bridges_json, encoding="utf-8") as fh:
            _bridges = json.load(fh)
    else:
        _bridges = [
            {"arg": "/cmd_vel@geometry_msgs/msg/Twist]gz.msgs.Twist", "remap": None},
            {"arg": "/clock@rosgraph_msgs/msg/Clock[gz.msgs.Clock", "remap": None},
        ]
    bridge_args = [b["arg"] for b in _bridges]
    bridge_remaps = [tuple(b["remap"]) for b in _bridges if b.get("remap")]

    # Spawn model name / height / fixed-base flag are compiled from the specs
    # (urdf/launch_config.json): the model spawns under the robot.yaml `name` (matching the sensor
    # bridges' scoped topics + the interface contract), and a fixed-base robot (e.g. an arm anchored
    # to the world frame) spawns without a -z drop. Fall back to the package name.
    launch_config = os.path.join(desc_share, "urdf", "launch_config.json")
    _cfg = json.load(open(launch_config, encoding="utf-8")) if os.path.exists(launch_config) else {}
    spawn_name = _cfg.get("robot_name", "warehouse_bot")
    spawn_args = ["-name", spawn_name, "-string", robot_desc]
    if not _cfg.get("fixed_base", False):
        spawn_args += ["-z", str(_cfg.get("spawn_z", 0.1))]

    # Headless Gazebo server: -s server-only, -r run unpaused, software rendering.
    gz = ExecuteProcess(
        cmd=["gz", "sim", "-s", "-r", "--headless-rendering", world],
        output="screen",
    )

    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        parameters=[{"robot_description": robot_desc}],
    )

    # Spawn the robot once the world is up.
    spawn = TimerAction(
        period=4.0,
        actions=[
            Node(
                package="ros_gz_sim",
                executable="create",
                output="screen",
                arguments=spawn_args,
            )
        ],
    )

    bridge = Node(
        package="ros_gz_bridge",
        executable="parameter_bridge",
        output="screen",
        arguments=bridge_args,
        remappings=bridge_remaps,
    )

    # Optional visualization: a Foxglove bridge, started only when gui:=foxglove.
    # Headless (gui:=none) stays the default; the scenario runner never enables it.
    foxglove = Node(
        package="foxglove_bridge",
        executable="foxglove_bridge",
        output="screen",
        parameters=[{"port": 8765, "address": "0.0.0.0"}],
        condition=IfCondition(EqualsSubstitution(LaunchConfiguration("gui"), "foxglove")),
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("gui", default_value="none"),
            gz,
            robot_state_publisher,
            bridge,
            spawn,
            foxglove,
        ]
    )
