<?xml version="1.0"?>
<package format="3">
  <name>drone_navigate</name>
  <version>0.1.0</version>
  <description>Warehouse bot controller (starter).</description>
  <maintainer email="robotbase@users.noreply.github.com">Robotbase</maintainer>
  <license>MIT</license>
  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <export><build_type>ament_python</build_type></export>
</package>
