from robotbase.robotspec.schema import RobotSpec
from robotbase.robotspec.compile import compile_robot


def test_custom_part_passes_urdf_through_verbatim(tmp_path):
    urdf = tmp_path / "my.urdf"
    urdf.write_text('<?xml version="1.0"?>\n<robot name="mine"><link name="base_link"/></robot>\n')
    spec = RobotSpec.model_validate(
        {"name": "mine", "parts": [{"use": "custom", "urdf": str(urdf)}]})
    c = compile_robot(spec)
    assert 'name="mine"' in c.urdf and '<link name="base_link"/>' in c.urdf
    assert "Generated by Robotbase" not in c.urdf          # verbatim — untouched


def test_imported_robot_still_gets_sensor_wiring(tmp_path):
    urdf = tmp_path / "my.urdf"
    urdf.write_text('<?xml version="1.0"?>\n<robot name="mine"><link name="base_link"/></robot>\n')
    spec = RobotSpec.model_validate(
        {"name": "mine", "parts": [{"use": "custom", "urdf": str(urdf)}],
         "sensors": [{"type": "lidar"}]})
    c = compile_robot(spec)
    assert any("/scan" in b.arg for b in c.bridges)         # bridge added…
    assert "gz-sim-sensors-system" in c.world_systems       # …system derived…
    assert "/scan" in c.manifest["ready_topics"]            # …manifest updated…
    assert 'type="gpu_lidar"' not in c.urdf                 # …but XML NOT injected (trusts the URDF)
