import os
import xml.dom.minidom
import tempfile
from robotbase.generator import create_project, template_dir


def test_create_compiles_specs_into_the_project():
    with tempfile.TemporaryDirectory() as tmp:
        dest = create_project("spec-bot", tmp, template_dir("differential-drive"))
        urdf = os.path.join(dest, "src", "spec_bot_description", "urdf", "spec_bot.urdf.xacro")
        world = os.path.join(dest, "src", "spec_bot_description", "worlds", "warehouse.sdf")
        assert os.path.exists(urdf) and os.path.exists(world)
        urdf_text = open(urdf, encoding="utf-8").read()
        world_text = open(world, encoding="utf-8").read()
        # compiled URDF is named after the project and generated by Robotbase
        assert 'name="spec_bot"' in urdf_text
        assert "Generated by Robotbase" in urdf_text
        assert 'type="gpu_lidar"' in urdf_text and 'type="contact"' in urdf_text
        # compiled world is well-formed, has physics + the robot-derived sensor systems
        xml.dom.minidom.parseString(world_text)
        assert "gz-sim-sensors-system" in world_text and "gz-sim-contact-system" in world_text
        assert "<max_step_size>0.001</max_step_size>" in world_text
