from robotbase.robotspec.schema import RobotSpec
from robotbase.robotspec.compile import compile_robot


def test_custom_part_passes_urdf_through_verbatim(tmp_path):
    urdf = tmp_path / "my.urdf"
    urdf.write_text('<?xml version="1.0"?>\n<robot name="mine"><link name="base_link"/></robot>\n')
    spec = RobotSpec.model_validate(
        {"name": "mine", "parts": [{"use": "custom", "urdf": str(urdf)}]})
    c = compile_robot(spec)
    assert 'name="mine"' in c.urdf and '<link name="base_link"/>' in c.urdf
    assert "Generated by Robotbase" not in c.urdf          # verbatim — untouched


def test_imported_robot_gets_sensor_wiring_and_injected_xml(tmp_path):
    # Adding a sensor to an imported URDF must inject the gz <sensor> XML too — otherwise the
    # bridge exists but nothing publishes (a silent /scan). Regression for the import+add-sensor
    # dogfooding bug: the imported body is preserved verbatim, the sensor is appended.
    urdf = tmp_path / "my.urdf"
    urdf.write_text('<?xml version="1.0"?>\n<robot name="mine"><link name="base_link"/></robot>\n')
    spec = RobotSpec.model_validate(
        {"name": "mine", "parts": [{"use": "custom", "urdf": str(urdf)}],
         "sensors": [{"type": "lidar"}]})
    c = compile_robot(spec)
    assert any("/scan" in b.arg for b in c.bridges)         # bridge added…
    assert "gz-sim-sensors-system" in c.world_systems       # …system derived…
    assert "/scan" in c.manifest["ready_topics"]            # …manifest updated…
    assert 'type="gpu_lidar"' in c.urdf                     # …AND the gz <sensor> XML injected
    assert '<link name="lidar_link"' in c.urdf              # …with its link
    assert '<link name="base_link"/>' in c.urdf             # original body preserved verbatim
