import os
import xml.dom.minidom
import tempfile
from robotbase.generator import create_project, template_dir


def test_create_compiles_specs_into_the_project():
    with tempfile.TemporaryDirectory() as tmp:
        dest = create_project("spec-bot", tmp, template_dir("differential-drive"))
        urdf = os.path.join(dest, "src", "spec_bot_description", "urdf", "spec_bot.urdf.xacro")
        world = os.path.join(dest, "src", "spec_bot_description", "worlds", "warehouse.sdf")
        assert os.path.exists(urdf) and os.path.exists(world)
        urdf_text = open(urdf, encoding="utf-8").read()
        world_text = open(world, encoding="utf-8").read()
        # compiled URDF is named after the project and generated by Robotbase
        assert 'name="spec_bot"' in urdf_text
        assert "Generated by Robotbase" in urdf_text
        assert 'type="gpu_lidar"' in urdf_text and 'type="contact"' in urdf_text
        # compiled world is well-formed, has physics + the robot-derived sensor systems
        xml.dom.minidom.parseString(world_text)
        assert "gz-sim-sensors-system" in world_text and "gz-sim-contact-system" in world_text
        assert "<max_step_size>0.001</max_step_size>" in world_text


def test_create_from_urdf_wraps_the_imported_urdf():
    import os, tempfile
    from robotbase.generator import create_project, template_dir
    with tempfile.TemporaryDirectory() as tmp:
        src_urdf = os.path.join(tmp, "mine.urdf")
        marker = '<?xml version="1.0"?>\n<robot name="mine"><link name="base_link"/><!--IMPORTED--></robot>\n'
        open(src_urdf, "w").write(marker)
        dest = create_project("imp-bot", tmp, template_dir("differential-drive"), from_urdf=src_urdf)
        placed = os.path.join(dest, "src", "imp_bot_description", "urdf", "imp_bot.urdf.xacro")
        assert open(placed, encoding="utf-8").read() == marker      # imported URDF is used verbatim
        robot_yaml = open(os.path.join(dest, "robot.yaml"), encoding="utf-8").read()
        assert "use: custom" in robot_yaml


def test_create_from_urdf_infers_sensors_into_world_systems():
    """Dogfood B: an imported URDF that declares a LiDAR must make the compiled world load the
    Sensors system, or the LiDAR never publishes. The importer infers sensors from the URDF."""
    with tempfile.TemporaryDirectory() as tmp:
        src_urdf = os.path.join(tmp, "r.urdf")
        open(src_urdf, "w").write(
            '<?xml version="1.0"?>\n<robot name="r"><link name="base_link"/>'
            '<gazebo reference="base_link"><sensor name="l" type="gpu_lidar"><topic>scan</topic>'
            '</sensor></gazebo></robot>\n')
        dest = create_project("imp2", tmp, template_dir("differential-drive"), from_urdf=src_urdf)
        robot_yaml = open(os.path.join(dest, "robot.yaml"), encoding="utf-8").read()
        assert "type: lidar" in robot_yaml                          # sensor inferred from the URDF
        world = open(os.path.join(dest, "src", "imp2_description", "worlds", "warehouse.sdf"),
                     encoding="utf-8").read()
        assert "gz-sim-sensors-system" in world                     # …so the world loads its system


def test_arm_compiles_from_specs():
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        dest = create_project("arm-bot", tmp, template_dir("arm"))
        urdf = open(os.path.join(dest, "src", "arm_bot_description", "urdf", "arm_bot.urdf.xacro"),
                    encoding="utf-8").read()
        assert "shoulder_joint" in urdf and "elbow_joint" in urdf
        assert "JointPositionController" in urdf and "arm_base_link" in urdf


def test_drone_compiles_from_specs():
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        dest = create_project("drone-bot", tmp, template_dir("drone"))
        urdf = open(os.path.join(dest, "src", "drone_bot_description", "urdf", "drone_bot.urdf.xacro"),
                    encoding="utf-8").read()
        assert "VelocityControl" in urdf and "rotor_fl" in urdf and 'type="imu"' in urdf
        world = open(os.path.join(dest, "src", "drone_bot_description", "worlds", "warehouse.sdf"),
                     encoding="utf-8").read()
        assert "gz-sim-imu-system" in world      # the declared imu pulls in its world system


def test_camera_bot_compiles_camera_and_depth():
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        dest = create_project("cam-bot", tmp, template_dir("camera-bot"))
        urdf = open(os.path.join(dest, "src", "cam_bot_description", "urdf", "cam_bot.urdf.xacro"),
                    encoding="utf-8").read()
        assert 'type="camera"' in urdf and 'type="depth_camera"' in urdf
        world = open(os.path.join(dest, "src", "cam_bot_description", "worlds", "warehouse.sdf"),
                     encoding="utf-8").read()
        assert "gz-sim-sensors-system" in world
