"""The SDF backend — the ONLY place world SDF strings are produced (P4).

``render_sdf`` reproduces byte-for-byte what ``worldspec.compile_world`` used to emit inline
(guarded by tests/test_golden_output.py's *.sdf fixtures).
"""
from __future__ import annotations

from xml.sax.saxutils import escape

from robotbase.worldspec.semantic import Box, Cylinder, Plane, StaticModel, WorldModel

# gz system filename -> plugin class name, and the few systems that carry a body.
_SYSTEM_NAMES = {
    "gz-sim-physics-system": "gz::sim::systems::Physics",
    "gz-sim-user-commands-system": "gz::sim::systems::UserCommands",
    "gz-sim-scene-broadcaster-system": "gz::sim::systems::SceneBroadcaster",
    "gz-sim-sensors-system": "gz::sim::systems::Sensors",
    "gz-sim-imu-system": "gz::sim::systems::Imu",
    "gz-sim-contact-system": "gz::sim::systems::Contact",
}
_SYSTEM_BODY = {"gz-sim-sensors-system": "<render_engine>ogre2</render_engine>"}


def _f(v):
    return f"{round(v, 6):g}"


def _esc(s):
    return escape(str(s), {'"': "&quot;"})


def _geom(g) -> str:
    if isinstance(g, Box):
        x, y, z = g.size
        return f"<box><size>{_f(x)} {_f(y)} {_f(z)}</size></box>"
    if isinstance(g, Cylinder):
        return f"<cylinder><radius>{_f(g.radius)}</radius><length>{_f(g.length)}</length></cylinder>"
    return f"<plane><normal>{g.normal}</normal><size>{g.size}</size></plane>"


def _model(m: StaticModel) -> str:
    geom = _geom(m.geometry)
    collision = f'<collision name="c"><geometry>{geom}</geometry></collision>' if m.has_collision else ""
    material = m.material or ""
    return (f'\n    <model name="{_esc(m.name)}"><static>true</static>'
            f'<pose>{_f(m.x)} {_f(m.y)} {_f(m.z)} 0 0 {_f(m.yaw)}</pose><link name="link">'
            f'{collision}<visual name="v"><geometry>{geom}</geometry>{material}</visual></link></model>')


def render_sdf(world: WorldModel) -> str:
    """Assemble the whole <sdf><world>: physics + systems + light + static models + includes."""
    sys_xml = "".join(
        f'\n    <plugin filename="{s}" name="{_SYSTEM_NAMES.get(s, s)}">{_SYSTEM_BODY.get(s, "")}</plugin>'
        for s in world.systems)
    body = ""
    if world.sun:
        body += ('\n    <light type="directional" name="sun"><cast_shadows>true</cast_shadows>'
                 '<pose>0 0 10 0 0 0</pose><diffuse>0.8 0.8 0.8 1</diffuse>'
                 '<direction>-0.5 0.1 -0.9</direction></light>')
    for m in world.models:
        body += _model(m)
    for uri in world.includes:
        body += f'\n    <include><uri>{_esc(uri)}</uri></include>'
    physics = ('\n    <physics name="default" type="ignored">'
               '<max_step_size>0.001</max_step_size><real_time_factor>1.0</real_time_factor></physics>')
    return (f'<?xml version="1.0"?>\n'
            f'<!-- Generated by Robotbase from world.yaml — edit the spec, not this file. -->\n'
            f'<sdf version="1.10">\n  <world name="{_esc(world.name)}">{physics}{sys_xml}{body}\n  </world>\n</sdf>\n')
