"""Merge Fragments into one validated robot and render the URDF (see declarative-compiler.md)."""
from __future__ import annotations

from robotbase.robotspec.ir import Fragment, JointIR


class InvalidAssembly(ValueError):
    ...


def fixed_joint(name, parent, child, xyz="0 0 0", rpy="0 0 0") -> JointIR:
    xml = (f'\n  <joint name="{name}" type="fixed">'
           f'<parent link="{parent}"/><child link="{child}"/>'
           f'<origin xyz="{xyz}" rpy="{rpy}"/></joint>')
    return JointIR(name, xml, parent=parent, child=child)


def _validate(root: str, links, joints):
    names = [l.name for l in links]
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        raise InvalidAssembly(f"duplicate link name(s): {sorted(dupes)}")
    jnames = [j.name for j in joints]
    jdupes = {n for n in jnames if jnames.count(n) > 1}
    if jdupes:
        raise InvalidAssembly(f"duplicate joint name(s): {sorted(jdupes)}")
    linkset = set(names)
    if root not in linkset:
        raise InvalidAssembly(f"root link {root!r} not present")
    child_of = {}
    for j in joints:
        if j.parent not in linkset:
            raise InvalidAssembly(f"joint {j.name!r} references missing parent link {j.parent!r}")
        if j.child not in linkset:
            raise InvalidAssembly(f"joint {j.name!r} references missing child link {j.child!r}")
        if j.child in child_of:
            raise InvalidAssembly(f"link {j.child!r} has two parent joints")
        child_of[j.child] = j.parent
    if root in child_of:
        raise InvalidAssembly(f"root link {root!r} must not be a child of any joint (cycle through root)")
    # every non-root link must reach root by walking child->parent
    for n in linkset:
        if n == root:
            continue
        seen, cur = set(), n
        while cur != root:
            if cur not in child_of:
                raise InvalidAssembly(f"link {n!r} is not connected to root {root!r} (orphan)")
            if cur in seen:
                raise InvalidAssembly(f"cycle detected at link {cur!r}")
            seen.add(cur)
            cur = child_of[cur]


def merge_and_render(name: str, root: str, fragments: list[Fragment]) -> tuple[str, list, list[str], dict]:
    links, joints, gazebo, bridges = [], [], [], []
    world_systems, ready_topics = [], []
    control, fixed_base, sensors = None, None, {}
    for f in fragments:
        links += f.links
        joints += f.joints
        gazebo += f.gazebo
        bridges += f.bridges
        for s in f.world_systems:
            if s not in world_systems:
                world_systems.append(s)
        for t in f.ready_topics:
            if t not in ready_topics:
                ready_topics.append(t)
        if f.control is not None:
            control = f.control
        if f.fixed_base is not None:
            fixed_base = f.fixed_base
        sensors.update(f.manifest_sensors)

    _validate(root, links, joints)

    urdf = (f'<?xml version="1.0"?>\n'
            f'<!-- Generated by Robotbase from robot.yaml — edit the spec, not this file. -->\n'
            f'<robot name="{name}" xmlns:xacro="http://ros.org/wiki/xacro">'
            + "".join(l.xml for l in links)
            + "".join(j.xml for j in joints)
            + "".join(gazebo)
            + "\n</robot>\n")
    manifest = {"control": control, "ready_topics": ready_topics,
                "fixed_base": fixed_base, "sensors": sensors}
    return urdf, bridges, world_systems, manifest
