"""Render the launch file from a CompiledRobot — the bridge wiring (with the contact remap)
and the spawn. The world/scenarios/starter controller come from the template or the world
spec; this is the part that depends on the robot's compiled sensors/control."""
from __future__ import annotations

from robotbase.robotspec.compile import CompiledRobot

_LAUNCH = '''import os

import xacro
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, ExecuteProcess, TimerAction
from launch.conditions import IfCondition
from launch.substitutions import EqualsSubstitution, LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    # Generated by Robotbase from robot.yaml — edit the spec, not this file.
    desc_share = get_package_share_directory("{name}_description")
    world = os.path.join(desc_share, "worlds", "warehouse.sdf")
    urdf_xacro = os.path.join(desc_share, "urdf", "{name}.urdf.xacro")
    robot_desc = xacro.process_file(urdf_xacro).toxml()

    gz = ExecuteProcess(
        cmd=["gz", "sim", "-s", "-r", "--headless-rendering", world], output="screen")
    robot_state_publisher = Node(
        package="robot_state_publisher", executable="robot_state_publisher", output="screen",
        parameters=[{{"robot_description": robot_desc}}])
    spawn = TimerAction(period=4.0, actions=[Node(
        package="ros_gz_sim", executable="create", output="screen",
        arguments=["-name", "{name}", "-string", robot_desc, "-z", "{spawn_z}"])])
    bridge = Node(
        package="ros_gz_bridge", executable="parameter_bridge", output="screen",
        arguments=[
            {args}
        ],
        remappings=[{remaps}],
    )
    foxglove = Node(
        package="foxglove_bridge", executable="foxglove_bridge", output="screen",
        parameters=[{{"port": 8765, "address": "0.0.0.0"}}],
        condition=IfCondition(EqualsSubstitution(LaunchConfiguration("gui"), "foxglove")))
    return LaunchDescription([
        DeclareLaunchArgument("gui", default_value="none"),
        gz, robot_state_publisher, bridge, spawn, foxglove])
'''


def render_launch(compiled: CompiledRobot) -> str:
    args = ",\n            ".join(f'"{b.arg}"' for b in compiled.bridges)
    remaps = ", ".join(f'("{f}", "{t}")' for b in compiled.bridges if b.remap
                       for f, t in [b.remap])
    return _LAUNCH.format(name=compiled.name, spawn_z=compiled.spawn_z, args=args, remaps=remaps)
