"""Compile a WorldSpec into a Gazebo SDF world (see docs/design/declarative-compiler.md).

The world always loads the base gz systems, unioned with the systems the robot's sensors
require (passed in as robot_systems) — the seam that keeps sensors declarative.
"""
from __future__ import annotations

import math
from xml.sax.saxutils import escape

from robotbase.worldspec.schema import WorldSpec

_BASE_SYSTEMS = ["gz-sim-physics-system", "gz-sim-user-commands-system",
                 "gz-sim-scene-broadcaster-system"]
_SYSTEM_NAMES = {
    "gz-sim-physics-system": "gz::sim::systems::Physics",
    "gz-sim-user-commands-system": "gz::sim::systems::UserCommands",
    "gz-sim-scene-broadcaster-system": "gz::sim::systems::SceneBroadcaster",
    "gz-sim-sensors-system": "gz::sim::systems::Sensors",
    "gz-sim-imu-system": "gz::sim::systems::Imu",
    "gz-sim-contact-system": "gz::sim::systems::Contact",
}
_SYSTEM_BODY = {"gz-sim-sensors-system": "<render_engine>ogre2</render_engine>"}


def _f(v):
    return f"{round(v, 6):g}"


def _esc(s):
    return escape(str(s), {'"': "&quot;"})


def _static_model(name, geom_xml, x, y, z, yaw=0.0):
    return (f'\n    <model name="{name}"><static>true</static>'
            f'<pose>{_f(x)} {_f(y)} {_f(z)} 0 0 {_f(yaw)}</pose><link name="link">'
            f'<collision name="c"><geometry>{geom_xml}</geometry></collision>'
            f'<visual name="v"><geometry>{geom_xml}</geometry></visual></link></model>')


def compile_world(spec: WorldSpec, robot_systems=None):
    systems = list(_BASE_SYSTEMS)
    for s in (robot_systems or []):
        if s not in systems:
            systems.append(s)
    sys_xml = "".join(
        f'\n    <plugin filename="{s}" name="{_SYSTEM_NAMES.get(s, s)}">{_SYSTEM_BODY.get(s, "")}</plugin>'
        for s in systems)

    body = ""
    if spec.light == "sun":
        body += ('\n    <light type="directional" name="sun"><cast_shadows>true</cast_shadows>'
                 '<pose>0 0 10 0 0 0</pose><diffuse>0.8 0.8 0.8 1</diffuse>'
                 '<direction>-0.5 0.1 -0.9</direction></light>')
    if spec.ground:
        body += _static_model("ground_plane",
                              '<plane><normal>0 0 1</normal><size>100 100</size></plane>', 0, 0, 0)
    for i, o in enumerate(spec.obstacles):
        if o.shape == "box":
            geom = f'<box><size>{_f(o.size[0])} {_f(o.size[1])} {_f(o.size[2])}</size></box>'
        else:
            geom = f'<cylinder><radius>{_f(o.size[0])}</radius><length>{_f(o.size[1])}</length></cylinder>'
        body += _static_model(f"obstacle_{i}", geom, o.at[0], o.at[1], o.at[2])
    for i, w in enumerate(spec.walls):
        ax, ay = w.from_
        bx, by = w.to
        length = math.hypot(bx - ax, by - ay)
        yaw = math.atan2(by - ay, bx - ax)
        geom = f'<box><size>{_f(length)} {_f(w.thickness)} {_f(w.height)}</size></box>'
        body += _static_model(f"wall_{i}", geom, (ax+bx)/2, (ay+by)/2, w.height/2, yaw)
    goals = {}
    for g in spec.goals:
        geom = f'<cylinder><radius>{_f(g.radius)}</radius><length>0.01</length></cylinder>'
        body += (f'\n    <model name="goal_{_esc(g.name)}"><static>true</static>'
                 f'<pose>{_f(g.at[0])} {_f(g.at[1])} 0.005 0 0 0</pose><link name="link">'
                 f'<visual name="v"><geometry>{geom}</geometry>'
                 '<material><ambient>0 1 0 0.3</ambient><diffuse>0 1 0 0.3</diffuse></material>'
                 '</visual></link></model>')
        goals[g.name] = {"at": g.at, "radius": g.radius}
    for uri in spec.include:
        body += f'\n    <include><uri>{_esc(uri)}</uri></include>'

    physics = ('\n    <physics name="default" type="ignored">'
               '<max_step_size>0.001</max_step_size><real_time_factor>1.0</real_time_factor></physics>')
    sdf = (f'<?xml version="1.0"?>\n'
           f'<!-- Generated by Robotbase from world.yaml — edit the spec, not this file. -->\n'
           f'<sdf version="1.10">\n  <world name="{_esc(spec.name)}">{physics}{sys_xml}{body}\n  </world>\n</sdf>\n')
    return sdf, {"goals": goals}
